//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMF.Transformations.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMF.Transformations.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The output of this computation has been delayed. Please subscribe to the OutputInitialized event to get informed when the Output has been created. If you were using the trace functionality, consider using the Trace methods to get the computation objects and wait until the output has been created. Alternatively, change the structure of your transformation rules to ensure that this computation has been initialized when you are making your request. ähnelt.
        /// </summary>
        internal static string ErrComputationOutputDelayed {
            get {
                return ResourceManager.GetString("ErrComputationOutputDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To instantiate a transformation rule, the current transformation rule must be an assignable of the specified transformation rule. ähnelt.
        /// </summary>
        internal static string ErrMarkInstantiatingForMustInherit {
            get {
                return ResourceManager.GetString("ErrMarkInstantiatingForMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The rule already instantiates another rule. Transformation rules must not instantiate multiple other transformation rules. ähnelt.
        /// </summary>
        internal static string ErrMarkInstantiatingForOneRuleAtMost {
            get {
                return ResourceManager.GetString("ErrMarkInstantiatingForOneRuleAtMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To require a transformation rule without specifying a selector, the current transformation rule must be assignable of the specified transformation rule. ähnelt.
        /// </summary>
        internal static string ErrRequiresTransNoSelectorMustInherit {
            get {
                return ResourceManager.GetString("ErrRequiresTransNoSelectorMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The collection of created rules returned a null instance. This is not allowed. Please change the implementation to return a meaningful collection of transformation rules. ähnelt.
        /// </summary>
        internal static string ErrTransformationCreateRulesNull {
            get {
                return ResourceManager.GetString("ErrTransformationCreateRulesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The rules must be created and registered, before the transformation can be set initialized ähnelt.
        /// </summary>
        internal static string ErrTransformationSetIsInitializedNoRulesRegistered {
            get {
                return ResourceManager.GetString("ErrTransformationSetIsInitializedNoRulesRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The rules must be created, before they can be set initialized. ähnelt.
        /// </summary>
        internal static string ErrTransformationSetIsRulesInitializedNoRulesCreated {
            get {
                return ResourceManager.GetString("ErrTransformationSetIsRulesInitializedNoRulesCreated", resourceCulture);
            }
        }
    }
}
