//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMF.Transformations.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMF.Transformations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was no instantiating rule for an element of type {0}. Consider creating a transformation rule for this case and mark it instantiating for the {1}-rule ähnelt.
        /// </summary>
        internal static string ErrAbstractRuleCreateOutput {
            get {
                return ResourceManager.GetString("ErrAbstractRuleCreateOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was no instantiating rule for elements of type {0} and {1}. Consider creating a transformation rule for this case and mark it instantiating for the {2}-rule ähnelt.
        /// </summary>
        internal static string ErrAbstractRuleT2CreateOutput {
            get {
                return ResourceManager.GetString("ErrAbstractRuleT2CreateOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To call a transformation rule without specifying a selector, the input type TRequiredInput must be an assignable of TIn and the output type TRequiredOutput must be an assignable of TOut ähnelt.
        /// </summary>
        internal static string ErrCall1ArgNoSelectorMustInherit {
            get {
                return ResourceManager.GetString("ErrCall1ArgNoSelectorMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To call a transformation rule without specifying a selector, the input type TRequiredInput1 must be an assignable of TIn1, the input type TRequiredInput2 must be an assignable type of TIn2 and the output type TRequiredOutput must be an assignable of TOut ähnelt.
        /// </summary>
        internal static string ErrCall2ArgNoSelectorMustInherit {
            get {
                return ResourceManager.GetString("ErrCall2ArgNoSelectorMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To call a transformation rule without specifying a selector, the input type of the transformation must be an assignable of TIn and the output must be an assignable of TOut ähnelt.
        /// </summary>
        internal static string ErrCallTransNoSelectorMustInherit {
            get {
                return ResourceManager.GetString("ErrCallTransNoSelectorMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To call a transformation rule without specifying a selector, the input types of the transformation must be assignables of TIn1 and TIn2 and the output must be an assignable of TOut ähnelt.
        /// </summary>
        internal static string ErrCallTransT2NoSelectorMustInherit {
            get {
                return ResourceManager.GetString("ErrCallTransT2NoSelectorMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The output of this computation has been delayed. Please subscribe to the OutputInitialized event to get informed when the Output has been created. If you were using the trace functionality, consider using the Trace methods to get the computation objects and wait until the output has been created. Alternatively, change the structure of your transformation rules to ensure that this computation has been initialized when you are making your request. ähnelt.
        /// </summary>
        internal static string ErrComputationOutputDelayed {
            get {
                return ResourceManager.GetString("ErrComputationOutputDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To instantiate transformation rules, the input type TRequiredInput must be an assignable of TIn and the output type TRequiredOutput must be an assignable of TOut ähnelt.
        /// </summary>
        internal static string ErrMarkInstantiating1ArgMustInherit {
            get {
                return ResourceManager.GetString("ErrMarkInstantiating1ArgMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To instantiate transformation rules, the input type TRequiredInput1 must be an assignable of TIn1, the input type TRequiredInput2 must be an assignable of TIn2 and the output type TRequiredOutput must be an assignable of TOut ähnelt.
        /// </summary>
        internal static string ErrMarkInstantiating2ArgMustInherit {
            get {
                return ResourceManager.GetString("ErrMarkInstantiating2ArgMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To instantiate a transformation rule, the input type of the transformation must be an assignable of TIn and the output must be an assignable of TOut ähnelt.
        /// </summary>
        internal static string ErrMarkInstantiatingMustInherit {
            get {
                return ResourceManager.GetString("ErrMarkInstantiatingMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To instantiate a transformation rule, the input types of the transformation must be assignables of TIn1 and TIn2 and the output must be an assignable of TOut ähnelt.
        /// </summary>
        internal static string ErrMarkInstantiatingMustInheritT2 {
            get {
                return ResourceManager.GetString("ErrMarkInstantiatingMustInheritT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This transformation already contains a rule of type {0}. Reflective transformation must not contain more than one rule per rule type. ähnelt.
        /// </summary>
        internal static string ErrReflectiveTransformationCustomRulesRuleTypeAlreadyInUse {
            get {
                return ResourceManager.GetString("ErrReflectiveTransformationCustomRulesRuleTypeAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The rule {0} cannot override the rule {1} because {0} does not inherit from {1}. ähnelt.
        /// </summary>
        internal static string ErrReflectiveTransformationOverrideNoInheritance {
            get {
                return ResourceManager.GetString("ErrReflectiveTransformationOverrideNoInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To require a transformation rule without specifying a selector, the input type TRequiredInput must be an assignable of TIn and the output type TRequiredOutput must be an assignable of TOut ähnelt.
        /// </summary>
        internal static string ErrRequires1ArgNoSelectorMustInherit {
            get {
                return ResourceManager.GetString("ErrRequires1ArgNoSelectorMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To require a transformation rule without specifying a selector, the input type TRequiredInput1 must be an assignable of TIn1, the input type TRequiredInput2 must be an assignable of TIn2 and the output type TRequiredOutput must be an assignable of TOut ähnelt.
        /// </summary>
        internal static string ErrRequires2ArgNoSelectorMustInherit {
            get {
                return ResourceManager.GetString("ErrRequires2ArgNoSelectorMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To require a transformation rule without specifying a selector, the input type of the transformation must be an assignable of TIn and the output must be an assignable of TOut ähnelt.
        /// </summary>
        internal static string ErrRequiresTransNoSelectorMustInherit {
            get {
                return ResourceManager.GetString("ErrRequiresTransNoSelectorMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To require a transformation rule without specifying a selector, the input types of the transformation must be assignables of TIn1 and TIn2 and the output must be an assignable of TOut ähnelt.
        /// </summary>
        internal static string ErrRequiresTransT2NoSelectorMustInherit {
            get {
                return ResourceManager.GetString("ErrRequiresTransT2NoSelectorMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified transformation rule to act as start rule is not a rule of the specified transformation! ähnelt.
        /// </summary>
        internal static string ErrTransformationEngineStartRuleNotRuleOfTransformation {
            get {
                return ResourceManager.GetString("ErrTransformationEngineStartRuleNotRuleOfTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The transformation rule {0} has been called with a wrong number of arguments. ähnelt.
        /// </summary>
        internal static string ErrTransformationRuleWrongNumberOfArguments {
            get {
                return ResourceManager.GetString("ErrTransformationRuleWrongNumberOfArguments", resourceCulture);
            }
        }
    }
}
