<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <RootNamespace>$(MSBuildProjectName.Replace("-dev", ""))</RootNamespace>
        <AssemblyName>$(MSBuildProjectName.Replace("-dev", ""))</AssemblyName>
        <SignAssembly>True</SignAssembly>
        <AssemblyOriginatorKeyFile>MDD4All_Github.snk</AssemblyOriginatorKeyFile>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="NMF.Collections">
        <HintPath>..\libs\NMF.Collections.dll</HintPath>
      </Reference>
      <Reference Include="NMF.Expressions">
        <HintPath>..\libs\NMF.Expressions.dll</HintPath>
      </Reference>
      <Reference Include="NMF.Expressions.Linq">
        <HintPath>..\libs\NMF.Expressions.Linq.dll</HintPath>
      </Reference>
      <Reference Include="NMF.Models">
        <HintPath>..\libs\NMF.Models.dll</HintPath>
      </Reference>
      <Reference Include="NMF.Serialization">
        <HintPath>..\libs\NMF.Serialization.dll</HintPath>
      </Reference>
      <Reference Include="NMF.Utilities">
        <HintPath>..\libs\NMF.Utilities.dll</HintPath>
      </Reference>
    </ItemGroup>




</Project>
